### ISSUE TITLE
Display the reason for litmus create agent failure 

### ISSUE THREAD

**Issue by vamsiammineni** [litmuschaos/litmusctl#109]
**Background:**

Litmusctl create agent uses kuberentes client internally to apply the generated manifest on the agent. But for some reason(mostly due to mismatch of the kubectl client version being used in litmusctl with the kubernetes verison I have in my cluster) litmuctl fail to apply the manifest on the cluster.  But I could not see any reason for the failure in the resulting printout.

```
Installation Mode: cluster
Applying YAML:
http://litmus-chaos-center.xxxx.xxx.xxxxxx.se/api/file/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyX2lkIjoiOGM2NDA3M2MtMDhlZi00OTU5LWExMzAtYzk5MGJhYmRiNWEwIn0.Md8F6sDb3reODR-iOYVB5_z9tEOfTOf9FDbRXz5aawlk.yaml
â Failed in applying connection yaml:

```

**Solution:**

I noticed in the code that the failure is due to kubectl apply -f failed to apply the patch. Here is where the code calls k8s.ApplyYaml method to apply the manifest. and the ApplyManifest method returns the yamlOutput and err(if the method fails to apply). But, in the message that is being printed when there is an error, It is just printing the yamlOutput which is empty incase of a failure.

**yamlOutput** should be replaced with **err**. So, a  proper error message is returned back to user for better understanding.

https://github.com/litmuschaos/litmusctl/blob/v0.8.0/pkg/cmd/create/agent.go

```
//Apply agent connection yaml
		yamlOutput, err := k8s.ApplyYaml(k8s.ApplyYamlPrams{
			Token:    agent.Data.UserAgentReg.Token,
			Endpoint: credentials.Endpoint,
			YamlPath: utils.ChaosYamlPath,
		}, kubeconfig, false)
		if err != nil {
			utils.White_B.Print("\n❌ Failed in applying connection yaml: \n" + yamlOutput)
			os.Exit(1)
		}
```

**Comment by SarthakJain26** [comment]
Hi @vamsiammineni , the error logging is already improved with v0.11.0
https://github.com/litmuschaos/litmusctl/blob/v0.11.0/pkg/cmd/connect/agent.go#L259
