### ISSUE TITLE
Make scenario parsing logic for `litmsuctl create scenario` command independent of `install-chaos-experiments` step

### ISSUE THREAD

**Issue by Jonsy13** [litmuschaos/litmusctl#113]
Generally the scenario manifests created via Chaos-Center contains an `install-chaos-experiments` step, which contains definition for all experiments users are going to run as part of that scenario. At the time of implementation of this feature (litmusctl create scenario), it was decided to use `install-chaos-experiments` step to fetch names of all experiments, users have added in the manifest.

But this can't be always the case, users may not have `install-chaos-experiments` step in their manifests while scheduling it via `litmusctl`.

When we upload a manifest in frontend, we had enhanced the logic in frontend by searching for templates which contains `kind: ChaosEngine` & fetch their names. Since a template containing `kind: ChaosEngine` denotes a chaos experiment. Same can be done in litmusctl making it independent of install-chaos-experiment.

For reference, how it's done in frontend - https://github.com/litmuschaos/litmus/blob/643f3bffb87a20fee209a77b842ad7eda01d1e54/litmus-portal/frontend/src/utils/yamlUtils.ts#L250

**Comment by Jonsy13** [comment]
Slack thread for reference - https://kubernetes.slack.com/archives/CNXNB0ZTN/p1669734627249449

**Comment by iamnicoj** [comment]
This issue can be closed based on PR #114

**Comment by Jonsy13** [comment]
Thanks @iamnicoj for this enhancement!! This is now released as part of `0.16.0` release of litmusctl.
