### ISSUE TITLE
litmusctl upgrade chaos-delegate fails with configmaps "agent-config" not found 

### ISSUE THREAD

**Issue by aslafy-z** [litmuschaos/litmusctl#115]
Hello,
We encouter issues with the litmusctl upgrade CLI v0.14.0.

```shell
$ litmusctl upgrade chaos-delegate --chaos-delegate-id="5aac7d8a-a0da-4807-9cbf-9b98a7192507" --project-id="802932df-a056-40a1-ad97-cdb03abc4498"
❌ Failed upgrading Chaos Delegate: 
configmaps "agent-config" not found
```

I guess the issue is triggered by this failure looking up the said configmap: https://github.com/litmuschaos/litmusctl/blob/master/pkg/apis/upgrade.go#L111 
While looking at the API results (in the browser console), I see the agent namespace is well configured.
I tried setting the `--kubeconfig` field to a single context kubeconfig file with the current namespace set to the agent namespace, nothing works.

If you have any clue, feel free to share. I can gather additional data if you need so.

**Comment by Nageshbansal** [comment]
@aslafy-z can you try with the latest release now? and let us know if you're still facing the same issue.
