### ISSUE TITLE
Get chaos environments command

### ISSUE THREAD

**Issue by SarthakJain26** [litmuschaos/litmusctl#164]
Add a command to get a list of chaos environments in a project. 
`litmusctl get chaos-environment --project-id="" --environment-id=""`
`litmusctl list chaos-environment --project-id=""`

**Comment by shivam-Purohit** [comment]
hey @SarthakJain26 can I try this?

**Comment by SarthakJain26** [comment]
Hi @shivam-Purohit, Of course! I'm here to help if you need any guidance or have questions along the way. Good luck!

**Comment by shivam-Purohit** [comment]
> Hi @shivam-Purohit, Of course! I'm here to help if you need any guidance or have questions along the way. Good luck!

thanks!

**Comment by shivam-Purohit** [comment]
hey @SarthakJain26  I was able to connect ctl with the litmus chaos. Though I am able to use the get commands but unable to create projects, or connect with the infra. It says permission denied or some other error
This is what i get for 
`litmusctl connect chaos-infra`

error : after inputting the name , desc and id
`permission denied`

I used minikube for the chaos installation and chaos is running fine(webapp) I am able to create infra and experiments
Is it related to connecting to namespace as it is in minikube not local kubernetes?

**Comment by SarthakJain26** [comment]
@shivam-Purohit what is the error you are getting for create project command?

**Comment by shivam-Purohit** [comment]
> @shivam-Purohit what is the error you are getting for create project command?

I fixed it. I think we need to rebuild the app after setting up the account.

**Comment by Nageshbansal** [comment]
hey @shivam-Purohit , any updates on this issue?

**Comment by shivam-Purohit** [comment]
> hey @shivam-Purohit , any updates on this issue?

Opened a PR #170

**Comment by Nageshbansal** [comment]
@SarthakJain26 can we close ths now? I think it's been already implemented by @shivam-Purohit

**Comment by shivam-Purohit** [comment]
This can be closed.
