### ISSUE TITLE
litmusctl set-account doesn't work in non-interactive mode

### ISSUE THREAD

**Issue by ash-man** [litmuschaos/litmusctl#169]
Hello all, 

**it is in regard litmusctl 1.0.0** 

when I try to configure new account for litmusctl by providing following command 

./litmusctl config set-account --endpoint "https://<my_url>" --username "admin" --password "passwd" it's not created immediately and I'm prompted for all parameters again: 

✔ Host endpoint where litmus is installed: <my_url>
✔ Username [Default: admin]: █dmin
✔ Password: ******█

and finally got following message: 

account.username/admin configured
Error:  internal system error

But it seems like account is configured - at least I can schedule workflows etc. 

**But the problem is that non-interactive mode is not working in litmusctl 1.0.0 and I cannot automate this process.** 

Thanks in advance,

**Comment by SarthakJain26** [comment]
Thank you @ash-man for reporting this, we will fix this ASAP.

**Comment by ash-man** [comment]
@SarthakJain26 - thank you for prompt response. Do you have any ETA when new version of litmusctl (fixed) can be released ?

**Comment by SarthakJain26** [comment]
We have a release on 15th of every month, so you can expect the fix in the coming release.

**Comment by deep-poharkar** [comment]
sorry i saw it late @SarthakJain26 let me know if anything @Nageshbansal

**Comment by ash-man** [comment]
Hello, 

I have downloaded latest version of litmusctl (1.1.0) and tested it (I used MacOS version): 

./litmusctl version
Litmusctl version:  1.1.0
Compatible ChaosCenter versions:
[ '3.0.0' '3.1.0' '3.2.0' ]

./litmusctl config set-account -e "<my_url>" -u "admin" -p "<pasword>"" --skipSSL
Host endpoint where litmus is installed: <my_url>
Username [Default: admin]: admin
Password: **********

account.username/admin configured
Error:  internal system error

So, it seems we have the same issue. Can you please confirm that the fix was included in 1.1.0 ?

**Comment by ash-man** [comment]
Ahh... ok, I see that you have added "-n" flag for non-interactive mode. It works however I can see this error message (still)

account.username/admin configured
Error:  internal system error

**Comment by Nageshbansal** [comment]
@ash-man that's the issue with one of the chaos center api. We're working on that while this doesn't interfere with litmusctl.
