### ISSUE TITLE
litmusctl connect chaos-infra: failed to get the Infra registration token:

### ISSUE THREAD

**Issue by CindyLizi** [litmuschaos/litmusctl#174]
What happened:
Litmusctl version: 1.0.0

$litmusctl config set-account
Host endpoint where litmus is installed:
Username [Default: admin]: admin
Password: ******

account.username/admin configured
Error: internal system error

$litmusctl connect chaos-infra
...

❌ failed to get the Infra registration token:

there is issue https://github.com/litmuschaos/litmusctl/issues/169 on "litmusctl config set-account" error, i have the same issue before use "litmusctl connect chaos-infra"

not sure if the fix of issue 169 will resolve this issue or not.

**Comment by Nageshbansal** [comment]
Thanks @CindyLizi for reporting the issue. We're looking into it

**Comment by wbhagan** [comment]
Hi @Nageshbansal,
Also having a similar issue and, I'm on **Litmusctl version:  1.1.0**. 
Any ETA on when this issue will be resolved?

**Comment by Nageshbansal** [comment]
@wbhagan which version of litmus you're using?

**Comment by wbhagan** [comment]
That's 3.2.0 @Nageshbansal

**Comment by Nageshbansal** [comment]
Hey @wbhagan @CindyLizi , the issue have been resolved in `released-1.20`

**Comment by Nageshbansal** [comment]
Resoved by release 3.2.0. 
Thanks for reporting it :)
