### ISSUE TITLE
litmusctl to connect to chaos infrastrastructure: invalid apiVersion

### ISSUE THREAD

**Issue by wbhagan** [litmuschaos/litmusctl#180]
Litmus version: 3.3.0
Litmusctl version: 1.2.0

When setting up an account, although it says the account has been configured, an internal system error is being returned.
```
$ litmusctl config set-account --endpoint="http://my-test-endpoint" --username="admin" --password="password" --non-interactive

account.username/admin configured
Error:  internal system error

$ litmusctl connect chaos-infra
Project list:
1.  admin-project

Select a project [Range: 1-1]: 1

Installation Modes:
1. Cluster
2. Namespace

Select Mode [Default: cluster] [Range: 1-2]: 1

🏃 Running prerequisites check....ERROR:  exec plugin: invalid apiVersion "client.authentication.k8s.io/v1"
```
With respect to the account setup error, "Error:  internal system error", I see it was also being referred to in [#169 ](https://github.com/litmuschaos/litmusctl/issues/169) and that [it was being looked into](https://github.com/litmuschaos/litmusctl/issues/169#issuecomment-1857712723). Is it still being looked into?

**Comment by Nageshbansal** [comment]
Hey @wbhagan , thanks for reporting this issue. The issue #169 was resolved. But the error that you're getting is not related to the mentioned issue.

**Comment by Nageshbansal** [comment]
hey @wbhagan , thanks for reporting the issue. The error `internal system error` doesn't interfere with infra installation.

**Comment by wbhagan** [comment]
I see this is no longer an issue with the latest versions
```Litmus version: 3.4.0
Litmusctl version: 1.3.0```
Good one fellas
