### ISSUE TITLE
Automate tests in pre-commit hook script.

### ISSUE THREAD

**Issue by shivam-Purohit** [litmuschaos/litmusctl#196]
Currently we dont have any scripts to check for linting/ formatting error in local. I propose we should add a script to extract certain steps/command directly from .github/workflow  and execute them before committing. This will eliminate extra commit fixing the lint and format. This will also ensure each commit is independent and does not give any error. We can further expand it to run the tests before any push to ensure each commit is complete without any errors.

what we need:
A script to extract steps/commads ( probably python script  )

A script to execute the commands ( bash script ) `.precommit script` which can be symlink with git/hook/precommit 
`ln -s ../../.pre-commit .git/hooks/pre-commit` . This will automatically trigger on commit.

**Comment by aryan-bhokare** [comment]
hey @SarthakJain26 @shivam-Purohit can i help out in this one?

**Comment by shivam-Purohit** [comment]
sure what you will need is 
1. a script to extract the steps from the workflow ( python maybe)
we will need specific steps, to do that, we can use variable like `hook : precommit`
2. after that you can execute those steps in a different bash script
3. we can use symlink to link this script to github hook precommit which will run on each commit

you can ask if you have any more doubts

**Comment by aryan-bhokare** [comment]
Sure @shivam-Purohit I'll be linking up a commit ref to this soon.
