### ISSUE TITLE
Refactor the update command

### ISSUE THREAD

**Issue by shivam-Purohit** [litmuschaos/litmusctl#212]
Update command currently does not follow the command convention. we already have a version command we can just add this update command as subcommand for version command. It should look something like this
`litmusctl version update`

or we can just add a flag for updating
`litmusctl version --update`

this seems like a better approach for me

**Comment by shivam-Purohit** [comment]
I will refactor it for the update probe command

**Comment by SarthakJain26** [comment]
Looks good to me. @kartikaysaxena any views on this?

**Comment by milinddethe15** [comment]
Can I work on this?

**Comment by shivam-Purohit** [comment]
@milinddethe15 you can go ahead and raise a pr. Just mention this issue there.

**Comment by kartikaysaxena** [comment]
Sorry for being late here @SarthakJain26 , was busy recently, yeah I think it makes sense, would come up with a PR to enhance this feature.

**Comment by shivam-Purohit** [comment]
@kartikaysaxena you can raise a pr for that. Thank you!
