### ISSUE TITLE
Unable to run litmusctl.exe in windows

### ISSUE THREAD

**Issue by kiranreddyamk** [litmuschaos/litmusctl#24]
What is the path in windows to run litmusctl.exe ?
I am able to see only *.go files after cloning the repo.

**Comment by rajdas98** [comment]
@kiranreddyamk You can run the litmusctl.exe from the download directory or move the litmus.exe to your environment path.

**Comment by kiranreddyamk** [comment]
@rajdas98 
step-1:  I have cloned the git repo https://github.com/litmuschaos/litmusctl
step-2:  Not able to find litmusctl.exe inside the above repo in my local

Also, in readme, Installation section, To install the latest version of litmusctl follow the below steps:
When i click on click here getting below error
**For example :  l**itmusctl-windows-arm64 | Click here | Click here | Click here
_This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7E5B2K9KW067GFDG</RequestId>
<HostId>Qe8vA5GdVbwS2sFP0FkH2wcFmXNsElQMK5alpQW13m5fu7n/vQ43xMGuTb9FLluySHQDjnz4XtQ=</HostId>
</Error>_

The below link is not accessible, please check.
https://litmusctl-bucket.s3-eu-west-1.amazonaws.com/litmusctl-windows-arm64-master.tar.gz

**Comment by rajdas98** [comment]
@kiranreddyamk Please try this- 
v0.3.0- https://litmusctl-bucket.s3.eu-west-1.amazonaws.com/litmusctl-windows-arm-v0.3.0.tar.gz
master- https://litmusctl-bucket.s3.eu-west-1.amazonaws.com/litmusctl-windows-arm-master.tar.gz

**Comment by rajdas98** [comment]
Currently, we are not supporting arm64. It was a typo in the README.md

**Comment by kiranreddyamk** [comment]
Thank you @rajdas98 for fixing the links and access issues in README.md

I have tried litmusctl.exe in windows and I am getting below error while creating the external agent. 
version i am using is : litmusctl-windows-**amd64-v0.3.0**

C:\litmus_setup> .\litmusctl.exe create agent
File reading error open C:\Users\kankire/.**litmusconfig**: The system cannot find the file specified.

**Comment by rajdas98** [comment]
@kiranreddyamk you need configure the litmusctl before creating the agents.

Here are the steps for it- https://github.com/litmuschaos/litmusctl/blob/master/Usage.md#minimal-steps-to-create-an-agent

**Comment by kiranreddyamk** [comment]
Thank you @rajdas98 for sharing the pre-requisite step.

Please let me know how to activate the external agent ?
Currently agent status is displayed as "Pending"

![Pending_Agent](https://user-images.githubusercontent.com/5388778/130173579-f88a6e52-1a97-4eec-a259-9a4b08be6ade.PNG)
