### ISSUE TITLE
Can't run litmusctl config set-account with a certificate signed by unknown authority

### ISSUE THREAD

**Issue by luigi-bitonti** [litmuschaos/litmusctl#42]
Can you add a --insecure flag to avoid the problem?
Thank you!

**Comment by rajdas98** [comment]
Hi, You can use this command for non-certificate endpoint or without SSL endpoint also. Can you share the response of this command?

**Comment by luigi-bitonti** [comment]
> Hi, You can use this command for non-certificate endpoint or without SSL endpoint also. Can you share the response of this command?

Thanks for the quick answer.
This is the error.

![image](https://user-images.githubusercontent.com/93377317/139833729-3b54edcd-7abc-4982-bdcd-d8813d0d2f1a.png)

**Comment by rajdas98** [comment]
@luigi-bitonti , there is no "--insecure" flag, can you apply with it.

**Comment by luigi-bitonti** [comment]
> @luigi-bitonti , there is no "--insecure" flag for litmusctl, can you apply without it.

![image](https://user-images.githubusercontent.com/93377317/139839159-ad5c0459-4a0f-4489-a046-5896e1aff91c.png)

**Comment by luigi-bitonti** [comment]
Are there news about the issue, guys?
