### ISSUE TITLE
Litmusctl Self-Signed Certificate Endpoint

### ISSUE THREAD

**Issue by yildirima** [litmuschaos/litmusctl#45]
Could you help me to disable SSL verification? Any way to disable SSL verification for the self signed certificate.

# litmusctl config set-account

Host endpoint where litmus is installed: https://litmus.apps.self.signed.com/

Username [Default: admin]:

Password: Post "https://litmus.apps.self.signed.com/auth/login": x509: certificate signed by unknown authority

**Comment by gdsoumya** [comment]
Hi @yildirima can you replace the image of your subscriber deployment and use `gdsoumya/litmusportal-subscriber:ci` image and set an extra env var in the deployment `SKIP_SSL_VERIFY : "true"` Let me know if that works for you, this should disable the SSL verification.

**Comment by luigi-bitonti** [comment]
> Hi @yildirima can you replace the image of your subscriber deployment and use `gdsoumya/litmusportal-subscriber:ci` image and set an extra env var in the deployment `SKIP_SSL_VERIFY : "true"` Let me know if that works for you, this should disable the SSL verification.

I tried and it gives always the same error of unknown authority.

**Comment by gdsoumya** [comment]
I have tested the changes it works fine, can you make sure you have properly edited the subscriber deployment to updated both the image and the env var @luigi-bitonti

**Comment by yildirima** [comment]
Also It doesnt fix my problem too. It must be an litmusctl option to disable self signed certificate control.

**Comment by yildirima** [comment]
1- I used this version but this flag shows unknown.

https://litmusctl-production-bucket.s3.amazonaws.com/litmusctl-linux-amd64-master.tar.gz

# litmusctl config set-account --skipSSL

Error: unknown flag: --skipSSL

**Comment by gdsoumya** [comment]
Try this https://github.com/litmuschaos/litmusctl/releases/tag/v0.6.0

**Comment by yildirima** [comment]
I want to know if you can compile it for us and add an S3 link like this?

https://litmusctl-production-bucket.s3.amazonaws.com/litmusctl-linux-amd64-master.tar.gz

**Comment by rajdas98** [comment]
@yildirima use this link- https://litmusctl-production-bucket.s3.amazonaws.com/litmusctl-linux-amd64-v0.6.0.tar.gz
